-- MySQL Script generated by MySQL Workbench
-- Thu May 29 13:07:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Crud_BD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Crud_BD` ;

-- -----------------------------------------------------
-- Schema Crud_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Crud_BD` DEFAULT CHARACTER SET utf8 ;
USE `Crud_BD` ;

-- -----------------------------------------------------
-- Table `Crud_BD`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crud_BD`.`Estudiante` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `grado` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_estudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crud_BD`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crud_BD`.`Proyecto` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` TEXT(500) NOT NULL,
  PRIMARY KEY (`id_proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crud_BD`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crud_BD`.`Docente` (
  `id_docente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `area` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_docente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crud_BD`.`Informe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crud_BD`.`Informe` (
  `id_actividad` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cantidad_horas` INT NOT NULL,
  `horas_acumuladas` INT NOT NULL,
  `trabajo_realizado` TEXT(500) NOT NULL,
  `Estudiante_id_estudiante` INT NOT NULL,
  `Proyecto_id_proyecto` INT NOT NULL,
  `Docente_id_docente` INT NOT NULL,
  PRIMARY KEY (`id_actividad`, `Estudiante_id_estudiante`, `Proyecto_id_proyecto`, `Docente_id_docente`),
  CONSTRAINT `fk_Informe_Estudiante1`
    FOREIGN KEY (`Estudiante_id_estudiante`)
    REFERENCES `Crud_BD`.`Estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Informe_Proyecto1`
    FOREIGN KEY (`Proyecto_id_proyecto`)
    REFERENCES `Crud_BD`.`Proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Informe_Docente1`
    FOREIGN KEY (`Docente_id_docente`)
    REFERENCES `Crud_BD`.`Docente` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Informe_Estudiante1_idx` ON `Crud_BD`.`Informe` (`Estudiante_id_estudiante` ASC) VISIBLE;

CREATE INDEX `fk_Informe_Proyecto1_idx` ON `Crud_BD`.`Informe` (`Proyecto_id_proyecto` ASC) VISIBLE;

CREATE INDEX `fk_Informe_Docente1_idx` ON `Crud_BD`.`Informe` (`Docente_id_docente` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
